repos:
-   repo: local
    hooks:
    -   id: stop-data-commit
        name: stop data commit
        entry: stop_data_hooks/stop_data_commit.py
        stages: [commit]
        language: python
        types: [python]